### PR TITLE
Merge data loaders from tgml to pytigergraph

### PR DESCRIPTION
**Pull request by tg-bill**
**Code changes:**
1. Add gds subpackage
2. Add various data loaders to the gds subpackage
3. Add unit tests for the data loaders
4. Add gds interface to `TigerGraphConnection` 

**Testing:**
Unit tests: passed
Integration tests: NA

**Docs:**
Docstring: available for all user-facing functions, some internal functions.
Examples: not included.

### CODE REVIEW

**Comment by parkererickson** [comment]
We need to add kafka to the requirements file (at least for GDS version of pyTG). I can setup the two dependency install - what requirements do we need?

Does the kafka option include authentication right now?

**Comment by tg-bill** [comment]
Great question. Let me make a minimal env file for it.

**Comment by parkererickson** [comment]
Another thing - the rest of pyTigerGraph uses camelCase for functions, the gds class currently does not (for example `neighborloader()`. Can we make this consistent to camelCase?

**Comment by tg-bill** [comment]
No problem. Just pushed a change for the camel cases

**Comment by tg-bill** [comment]
Just added the python env for development. It can also be used for testing.

**Review by parkererickson — COMMENTED** [review]
Looks good!

**Pull request merged**
